# define constants
ROUND_BONUS_GAMMA = 1
EATEN_BY_GHOST = -20
EAT_PACMAN = 30
DESTORY_PACMAN_SHIELD = 5
EAT_ALL_BEANS = 30
PREVENT_PACMAN_EAT_ALL_BEANS = 20

MAX_ROUND = 1000
OPERATION_NUM = 5
SPACE_CATEGORY = 9  # Note: 0:wall 1:empty 2:regular bean 3:bonus bean 4:speed bean 5:magnet bean 6:shield bean 7:*2 bean 8:portal
SKILL_NUM = 4

MAX_LEVEL = 3

MAX_AI_TIME = 1
MAX_PLAYER_TIME = 60
MAX_LENGTH = 1024